### ISSUE TITLE
adns3080

### ISSUE THREAD

**Issue by leixiaolin** [RCmags/ADNS3080_frame_capture#1]
// SPI pins:
#define PIN_RESET    45
#define PIN_CS       47

Dear sir:
pin_cs is which pin for adns3080?  It just has GND, 5V, 3V,NCS, MISO, MOSI, SCLK, RST, NPD, LED

**Comment by RCmags** [comment]
Hi!
If I remember correctly pin_cs refers to the NCS pin on the sensor.
