### ISSUE TITLE
black/empty output

### ISSUE THREAD

**Issue by Robin-Sch** [RCmags/ADNS3080_frame_capture#2]
The only output I get is black/empty unless I shine a very bright light at the sensor.

Even adjusting the focus doesn't change it. It always stays black/empty.

**Comment by RCmags** [comment]
Unfortunately that sounds like normal behavior. The sensor is meant to have a bright Led illuminating an adjacent surface (preferably White for max reflection). With this much light, you'll be able to properly focus the lens. I recommend small text as a surface to judge the image.

Also, the plastic lens may not retract enough to   focus. Remove about half a centimeter from the threads.

**Comment by Robin-Sch** [comment]
Do you think adding IR LED's (850/940 nm) would improve the quality of the camera?

**Comment by RCmags** [comment]
I doubt it. The sensor is less sensitive to red light so making it even redder won't help. Blue and yellow work well, but the best color I found was white. In any case, check the SQUAL value to see if a light/surface combination is adequate. The brighter/better the surface, the larger the value. Do note that if the value is too small the sensor won't output displacements.

**Comment by RCmags** [comment]
Be sure to remove the plastic tape covering the sensor opening. You will need to remove the lens to access the top of the chip. Otherwise you will surely not see anything!

**Comment by Robin-Sch** [comment]
> Also, the plastic lens may not retract enough to focus. Remove about half a centimeter from the threads.

I still have problems focusing the lens. Do you have any tips/recommendations besides removing half a centimeter from the threads?

And yeah, the plastic tape was still on the sensor opening.... Now it works really well except the focusing.

**Comment by RCmags** [comment]
Well the lens has to be pretty close to focus. Even then, its only good for objects 1cm or so from the sensor. Try cutting the plastic nut the lens screws onto. 5mm should be enough. 

If you want to focus on objects farther away, consider removing the lens altogether. Be careful to prevent dust from entering the sensor though!

**Comment by Robin-Sch** [comment]
yeah removing 5mm worked, it's working really well right now. Thank you so much
